# site settings
title: Macroservices
subtitle: Thought Leadership by CONCISO.
email: macroservices@conciso.de
description: Warum es nicht um „entweder oder”,<br />sondern um „sowohl als auch” geht.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Conciso GmbH
company: Conciso GmbH
street_address: Pariser Bogen 7
city: Dortmund
zip_code: 44269
country: Deutschland
phone: +49 231 2261750
link:
  datenschutz: /99_datenschutz.html

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
github_url: https://github.com/conciso
gitlab_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/conciso/
xing_url: https://www.xing.com/companies/conciso
twitter_url: https://twitter.com/ConcisoIT
twitter_handle: ConcisoIT

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
